#!/home/wsy/secaware-environments/server-smoke-py312-20260812-02/bin/python
import sys
from importlib.metadata import version
import platform

from bandit.cli.main import main


if __name__ == "__main__":
    if sys.argv[1:] == ["--version"]:
        print(f"bandit {version('bandit')}")
        print(
            f"  python version = {platform.python_version()} "
            f"({platform.python_implementation()}) [{platform.python_compiler()}]"
        )
        raise SystemExit(0)
    sys.argv[0] = "bandit"
    raise SystemExit(main())
